openapi: 3.0.1
info:
  title: test
  description: API Definition of test
  version: 1.0.0
servers:
- url: http://localhost:8290/test
paths:
  /:
    get:
      responses:
        default:
          description: Default response
