openapi: 3.0.1
info:
  title: arrayCount
  description: API Definition of arrayCount
  version: 1.0.0
servers:
- url: http://localhost:8290/array
paths:
  /:
    post:
      responses:
        default:
          description: Default response
