openapi: 3.0.1
info:
  title: business-logic
  description: API Definition of business-logic
  version: 1.0.0
servers:
- url: http://localhost:8290/custom
paths:
  /:
    get:
      responses:
        default:
          description: Default response
