openapi: 3.0.1
info:
  title: callOut
  description: API Definition of callOut
  version: 1.0.0
servers:
- url: http://localhost:8290/callOut
paths:
  /:
    get:
      responses:
        default:
          description: Default response
