openapi: 3.0.1
info:
  title: callApi
  description: API Definition of callApi
  version: 1.0.0
servers:
- url: http://localhost:8290/call
paths:
  /:
    get:
      responses:
        default:
          description: Default response
