openapi: 3.0.1
info:
  title: fileApi
  description: API Definition of fileCheck
  version: 1.0.0
servers:
- url: http://localhost:8290/fileCopy
paths:
  /:
    get:
      responses:
        default:
          description: Default response
