openapi: 3.0.1
info:
  title: RESTApi
  description: API Definition of RESTApi
  version: 1.0.0
servers:
- url: http://localhost:8290/api
paths:
  /unittests:
    get:
      responses:
        default:
          description: Default response
  /unittest:
    put:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
    delete:
      responses:
        default:
          description: Default response
